# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(default=0)),
                ('rest', models.CharField(default=0, max_length=20)),
            ],
            options={
                'ordering': ['no'],
            },
        ),
    ]
